vim.out.mouse=a
vim.out.noerrorbells
vim.out.clipboard=unnamed
vim.out.nocompatible
vim.out.backspace=indent,eol,start
vim.out.path+=**
vim.out.wildmenu
vim.out.belloff=all
vim.out.tabstop=4 softtabstop=4
vim.out.shiftwidth=4
vim.out.expandtab
vim.out.smartindent
vim.out.nu
vim.out.relativenumber
vim.out.nowrap
vim.out.smartcase
vim.out.noswapfile
vim.out.nobackup
vim.out.undodir=$HOME/vimfiles/undodir
vim.out.undofile
vim.out.incsearch
vim.out.scrolloff=8
vim.out.signcolumn=yes
vim.out.colorcolumn=90
vim.out.nobackup
vim.out.nowritebackup
vim.out.noswapfile
vim.out.clipboard=unnamed
vim.out.nocompatible
vim.out.path+=**
vim.out.wildmenu
